language: c

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gcc-arm-none-eabi

before_script:
  - ./common/ci/ci-install-sdk.sh

script:
  - find examples -name "armgcc" | xargs -Ixxx -n1 make clean all -C xxx xDK_TOP=/tmp/nrf52-sdk-for-travis-ci
  
  
  

  
