language: c

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential gcc-arm-none-eabi

script:
  - make -C examples/gpio_toggle/arm
  
  

  
